language: generic
dist: trusty
sudo: false

os:
  - linux

env:
  matrix:
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=3.6

before_install:
  - sudo apt-get update;
  - wget "http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes
  - conda update -q conda
  - conda create -q -n test-environment python=$PYTHON_VERSION pip numpy matplotlib
  - source activate test-environment
  - "pip install -q pytest"
  - "pip install -q coverage"
  - "pip install scrutinizer-ocular"
  - "pip install -r requirements.txt"
  - "conda list" # for debugging

install:
  - "pip install ."

script:
  - "coverage run --source=mrainet -m pytest"

after_script:
  - "ocular"
  
